# Generated by Django 5.2.3 on 2025-08-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('Octane', 'Octane'), ('Regalia', 'Regalia'), ('Raga', 'Raga'), ('Edge', 'Edge'), ('Neo', 'Neo'), ('Automatic', 'Automatic'), ('Karishma', 'Karishma'), ('Smartwatches', 'Smartwatches'), ('Nebula', 'Nebula'), ('Couple Watches', 'Couple Watches')], max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='store_images/')),
            ],
        ),
    ]
